In [16]:
pip install numpy


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy as np
arr=np.array([12,45,78,98,6,90,45,9,23])
arr

array([12, 45, 78, 98,  6, 90, 45,  9, 23])

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr.shape

(9,)

In [20]:
arr.itemsize

8

In [21]:
arr.nbytes

72

In [22]:
arr=np.arange(1,21,2,dtype='float32')
arr

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [23]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
arr=np.full((3,4),2)
arr

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [25]:
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr=np.loadtxt("weather_data.csv",delimiter=",",skiprows=1,
              usecols=[1,2,3])
arr.shape

FileNotFoundError: weather_data.csv not found.

In [ ]:
np.mean(arr,axis=0)

array([21.94520548, 50.30958904,  1.43068493])

In [ ]:
np.std(arr,axis=0)

array([ 7.35933739, 15.38563789,  1.77843731])

In [ ]:
arr=np.random.randint(1,100,12)
arr=np.reshape(arr,(3,4))
arr

array([[85,  7, 68, 35],
       [75, 13, 69, 46],
       [62, 55, 96, 25]])

In [ ]:
arr[1,2]

69

In [ ]:
arr[1:,0:3]

array([[75, 13, 69],
       [62, 55, 96]])

In [ ]:
arr[:,2]

array([68, 69, 96])

In [ ]:
arr[-2::1,-2::1]

array([[69, 46],
       [96, 25]])

In [ ]:
arr=np.random.randint(1,100,36)
arr=np.reshape(arr,(6,6))
print(arr)
arr[2::2,0::2]

[[79  1 31 32 99 64]
 [88 39 81 50 96 94]
 [34 53 77 47 21 40]
 [41 65 45  8 39 36]
 [ 7 12  8 28 15 87]
 [24 67 17  4  9 60]]


array([[34, 77, 21],
       [ 7,  8, 15]])

In [ ]:
# Fancy indexing
arr=np.array([12,45,67,89,90,67,43,61])
arr[[3,7,5,0]]

array([89, 61, 67, 12])

In [ ]:
arr=np.random.randint(1,100,30)
arr=np.reshape(arr,(5,6))
arr

array([[73, 36, 56, 59, 62, 53],
       [24,  6, 62, 87, 64, 40],
       [ 1, 44, 97, 11, 23, 25],
       [73,  3, 34, 36, 31,  1],
       [59,  3, 41, 71, 80, 26]])

In [ ]:
arr[[1,3,4],[1,4,0]]

array([ 6, 31, 59])

In [ ]:
arr=np.array([12,45,78,90,56])
# fetching data using boolean mask
mask=np.array([False,False,True,False,True])
arr[mask]

array([78, 56])

In [ ]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
marks=np.array([[78,89,78,90,78],[34,56,89,23,23],
                [45,56,34,67,34]])
np.mean(marks,axis=0)

array([52.33333333, 67.        , 67.        , 60.        , 45.        ])

In [ ]:
np.max(marks,axis=0)

array([78, 89, 89, 90, 78])

In [ ]:
arr=np.array([[67,34,78],[32,9,21],[34,89,23]])
np.unravel_index(np.argmax(arr),arr.shape)

(2, 1)

In [ ]:
# Lets print table of any number
 
def table(n):
    print(f"The Table of {n} is: ")
    for i in range(1,11):
        print(f"{n} x {i} = {n*i}")
    print()
numbers = input("Enter the numbers you want to the print the table separated by spaces: ").split(" ")
nums = list(map(int, numbers))

for num in nums:
    table(num)

The Table of 12 is: 
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120

The Table of 13 is: 
13 x 1 = 13
13 x 2 = 26
13 x 3 = 39
13 x 4 = 52
13 x 5 = 65
13 x 6 = 78
13 x 7 = 91
13 x 8 = 104
13 x 9 = 117
13 x 10 = 130

The Table of 14 is: 
14 x 1 = 14
14 x 2 = 28
14 x 3 = 42
14 x 4 = 56
14 x 5 = 70
14 x 6 = 84
14 x 7 = 98
14 x 8 = 112
14 x 9 = 126
14 x 10 = 140

The Table of 15 is: 
15 x 1 = 15
15 x 2 = 30
15 x 3 = 45
15 x 4 = 60
15 x 5 = 75
15 x 6 = 90
15 x 7 = 105
15 x 8 = 120
15 x 9 = 135
15 x 10 = 150

The Table of 16 is: 
16 x 1 = 16
16 x 2 = 32
16 x 3 = 48
16 x 4 = 64
16 x 5 = 80
16 x 6 = 96
16 x 7 = 112
16 x 8 = 128
16 x 9 = 144
16 x 10 = 160

The Table of 17 is: 
17 x 1 = 17
17 x 2 = 34
17 x 3 = 51
17 x 4 = 68
17 x 5 = 85
17 x 6 = 102
17 x 7 = 119
17 x 8 = 136
17 x 9 = 153
17 x 10 = 170

