### Arrays

#### 1. Array

In [1]:
import array

##### creation

In [2]:
arr1 = array.array('i', [10, 20, 30, 40, 50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [3]:
arr2 = array.array('i', [60, 70, 80])
print(arr2)

array('i', [60, 70, 80])


##### access

In [ ]:
arr1[2]

30

In [4]:
arr1[3]

40

##### traversal

In [ ]:
for element in arr1:
    print(element, end=" ")

10 20 30 40 50 

##### insertion

In [ ]:
arr1.insert(3, 35)

In [8]:
print(arr1)

array('i', [10, 20, 30, 35, 40, 50])


##### deletion

In [ ]:
arr1.remove(30)
print(arr1)

array('i', [10, 20, 35, 40, 50])


##### updation

In [ ]:
arr1[2] = 30
print(arr1)

array('i', [10, 20, 30, 40, 50])


##### sorting

In [ ]:
arr3 = array.array('i', [4, 7, 3, 9, 2, 6])
print(arr3)

array('i', [4, 7, 3, 9, 2, 6])


In [15]:
sorted_arr3 = array.array('i', sorted(arr3))
print(sorted_arr3)

array('i', [2, 3, 4, 6, 7, 9])


##### merging

In [ ]:
arr1

array('i', [10, 20, 30, 40, 50])

In [17]:
arr2

array('i', [60, 70, 80])

In [19]:
arr4 = arr1 + arr2
arr4

array('i', [10, 20, 30, 40, 50, 60, 70, 80])

##### splitting

In [ ]:
ix = int(len(arr4) / 2)
ix

4

In [24]:
arr4[:ix]

array('i', [10, 20, 30, 40])

In [25]:
arr4[ix:]

array('i', [50, 60, 70, 80])

#### 2. Numpy

In [5]:
import numpy as np

##### creation

In [6]:
np1 = np.array([10, 20, 30, 40, 50])
np2 = np.array([50, 60, 70])

print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70]


In [28]:
np1

array([10, 20, 30, 40, 50])

##### access

In [7]:
np1[0]

10

##### traversal

In [8]:
for ele in np1:
    print(ele, end=" ")

10 20 30 40 50 

##### insertion

In [9]:
np.insert(np1, 3, 35)

array([10, 20, 30, 35, 40, 50])

##### deletion

In [10]:
np.delete(np1, 3)

array([10, 20, 30, 50])

##### updation

In [11]:
np1[2] = 35
print(np1)

[10 20 35 40 50]


##### sorting

In [12]:
np3 = np.array([5, 3, 7, 6, 2, 9])
np3

array([5, 3, 7, 6, 2, 9])

In [13]:
np.sort(np3)

array([2, 3, 5, 6, 7, 9])

##### merging

In [14]:
np1

array([10, 20, 35, 40, 50])

In [15]:
np2

array([50, 60, 70])

In [16]:
np3 = np.concatenate((np1, np2))
np3

array([10, 20, 35, 40, 50, 50, 60, 70])

##### splitting

In [22]:
split1, split2, split3 = np.array_split(np3, 3)

In [23]:
split1

array([10, 20, 35])

In [24]:
split2

array([40, 50, 50])

In [25]:
split3

array([60, 70])

##### vectorization

In [26]:
np1

array([10, 20, 35, 40, 50])

In [27]:
np1 + 10

array([20, 30, 45, 50, 60])

In [28]:
np1 * 2

array([ 20,  40,  70,  80, 100])

In [54]:
np3 = np.array([4, 5])
np4 = np.array([6, 7])

np3 / np4

array([0.66666667, 0.71428571])

In [59]:
li1 = [4, 5, 6]
li2 = [1, 2, 3]

In [61]:
for i in range(len(li1)):
    print(li1[i] + li2[i])

5
7
9


In [62]:
for i in range(len(li1)):
    print(li1[i] + 10)

14
15
16
